color0 #131316
color1 #ffb4ab
color2 #e1c37d
color3 #c0c6da
color4 #b4c6f5
color5 #e1c37d
color6 #c0c6da
color7 #e4e2e6
color8 #8f9099
color9 #ffb4ab
color10 #e1c37d
color11 #c0c6da
color12 #b4c6f5
color13 #e1c37d
color14 #c0c6da
color15 #e4e2e6

cursor                #e4e2e6
cursor_text_color     #131316
background            #131316
foreground            #e4e2e6
selection_foreground  #c5c6cf
selection_background  #44464e
url_color             #b4c6f5