color0 #131313
color1 #ffb4ab
color2 #d6bee5
color3 #bac8db
color4 #9dcaff
color5 #d6bee5
color6 #bac8db
color7 #e2e2e2
color8 #919191
color9 #ffb4ab
color10 #d6bee5
color11 #bac8db
color12 #9dcaff
color13 #d6bee5
color14 #bac8db
color15 #e2e2e2

cursor                #e2e2e2
cursor_text_color     #131313
background            #131313
foreground            #e2e2e2
selection_foreground  #c6c6c6
selection_background  #474747
url_color             #9dcaff