color0 #131313
color1 #ffb4ab
color2 #7cd0ff
color3 #b5c9d7
color4 #cac1e9
color5 #7cd0ff
color6 #b5c9d7
color7 #e2e2e2
color8 #919191
color9 #ffb4ab
color10 #7cd0ff
color11 #b5c9d7
color12 #cac1e9
color13 #7cd0ff
color14 #b5c9d7
color15 #e2e2e2

cursor                #e2e2e2
cursor_text_color     #131313
background            #131313
foreground            #e2e2e2
selection_foreground  #c6c6c6
selection_background  #474747
url_color             #7cd0ff
