color0 #131313
color1 #ffb4ab
color2 #dcbce0
color3 #bec6dc
color4 #aac7ff
color5 #dcbce0
color6 #bec6dc
color7 #e2e2e2
color8 #919191
color9 #ffb4ab
color10 #dcbce0
color11 #bec6dc
color12 #aac7ff
color13 #dcbce0
color14 #bec6dc
color15 #e2e2e2

cursor                #e2e2e2
cursor_text_color     #131313
background            #131313
foreground            #e2e2e2
selection_foreground  #c6c6c6
selection_background  #474747
url_color             #aac7ff